import { NavbarComponent } from '@src/app/navbar/navbar.component';
import { ErrorHandler } from '@angular/core';
import { HttpModule } from '@angular/http';
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { EffectsModule } from '@ngrx/effects';
import { StoreModule } from '@ngrx/store';

import { AppRoutingModule } from '@src/app/app-routing.module';
import { AppComponent } from '@src/app/app.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { SupermarketComponent } from '@src/app/supermarket/supermarket.component';
import { SupermarketService } from '@src/app/services/supermarket.service';
import { AppErrorHandler } from '@src/app/common/app-error-handler';
import { MessageComponent } from '@src/app/message/message.component';
import { ProductComponent } from '@src/app/product/product.component';
import { LoginComponent } from '@src/app/login/login.component';
import { UserService } from '@src/app/services/user.service';
import { CategoryService } from '@src/app/services/category.service';
import { RegisterComponent } from '@src/app/register/register.component';
import { AuthEffects } from './store/effects/auth.effects';
import { reducers } from './store/app.states';
//import { DataService } from './services/data.service';

@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent,
    SupermarketComponent,
    MessageComponent,
    NavbarComponent,
    ProductComponent,
    LoginComponent,
    RegisterComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    FormsModule,
    ReactiveFormsModule,
    HttpModule,
    StoreModule.forRoot(reducers, {}),
    EffectsModule.forRoot([AuthEffects]),
  ],
  providers: [
      SupermarketService,
      CategoryService,
      UserService,
      { provide: ErrorHandler, useClass: AppErrorHandler }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
