import { NavbarComponent } from './navbar/navbar.component';
import { ErrorHandler } from '@angular/core';
import { HttpModule } from '@angular/http';
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';

import { AppRoutingModule } from '@src/app/app-routing.module';
import { AppComponent } from '@src/app/app.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { SupermarketComponent } from '@src/app/supermarket/supermarket.component';
import { SupermarketService } from '@src/app/services/supermarket.service';
import { AppErrorHandler } from '@src/app/common/app-error-handler';
import { MessageComponent } from '@src/app/message/message.component';
//import { DataService } from './services/data.service';

@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent,
    SupermarketComponent,
    MessageComponent,
    NavbarComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    FormsModule,
    HttpModule
  ],
  providers: [
      SupermarketService,
      { provide: ErrorHandler, useClass: AppErrorHandler }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
